//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_2210900084_project02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_GH
    {
        public int Ma_GH { get; set; }
        public int Ma_SP { get; set; }
        public int So_luong { get; set; }
    
        public virtual GIO_HANG GIO_HANG { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
