//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_2210900084_project02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_HANG()
        {
            this.CHI_TIET_DH = new HashSet<CHI_TIET_DH>();
        }
    
        public int Ma_DH { get; set; }
        public Nullable<int> Ma_KH { get; set; }
        public System.DateTime Ngay_dat { get; set; }
        public decimal Tong_tien { get; set; }
        public string Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_DH> CHI_TIET_DH { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
