//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_2210900084_project02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI
    {
        public int Ma_QL { get; set; }
        public string Ten_QL { get; set; }
        public string Email { get; set; }
        public string Mat_khau { get; set; }
    }
}
