//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_2210900084_project02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.CHI_TIET_DH = new HashSet<CHI_TIET_DH>();
            this.CHI_TIET_GH = new HashSet<CHI_TIET_GH>();
        }
    
        public int Ma_SP { get; set; }
        public string Ten_SP { get; set; }
        public decimal Gia { get; set; }
        public string Mo_ta { get; set; }
        public int So_luong { get; set; }
        public Nullable<int> Ma_DM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_DH> CHI_TIET_DH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_GH> CHI_TIET_GH { get; set; }
        public virtual DANH_MUC DANH_MUC { get; set; }
    }
}
